import { ReceiptTemplate, StoreSettings } from '../types';

export const createDefaultReceiptTemplate = (store?: Partial<StoreSettings>): ReceiptTemplate => ({
  // Header Settings
  showHeaderLogo: true,
  logoSize: 'medium',
  logoAlignment: 'center',
  storeNameText: store?.storeName || 'MY MEDICAL STORE',
  storeNameFontSize: 'large',
  storeNameBold: true,
  storeNameUppercase: true,
  storeNameAlignment: 'center',
  showTagline: true,
  taglineText: store?.tagline || 'Pharmacy & General Store',
  taglineAlignment: 'center',
  showAddress: true,
  addressText: store?.address || 'Main Market, Pakistan',
  addressAlignment: 'center',
  showPhone: true,
  phoneLabel: 'Ph:',
  phoneText: store?.phone || '0300-1234567',
  showTaxId: false,
  taxIdLabel: 'Drug Lic #:',
  taxIdText: 'DL-042-88192',

  // General Styling & Typography
  fontFamily: 'monospace',
  baseFontSize: 'standard',
  dividerStyle: 'dashed',
  paperPadding: 'normal',

  // Invoice Metadata Block
  showInvoiceNo: true,
  invoiceNoLabel: 'Inv#:',
  showDate: true,
  dateFormat: 'YYYY-MM-DD HH:mm:ss',
  showCashier: true,
  cashierLabel: 'Cashier:',
  showCustomerName: true,
  customerNameLabel: 'Customer:',
  showCustomerPhone: false,
  showCustomerAddress: false,
  showCustomerPreviousBalance: true,
  showSaleType: true,
  showPaperSizeTag: true,

  // Items Section
  itemLayout: 'standard_table',
  colNameLabel: 'Item Name',
  colQtyLabel: 'Qty',
  colRateLabel: 'Rate',
  colDiscountLabel: 'Disc',
  colAmountLabel: 'Amt',
  showItemDiscount: false,
  showBatchNo: false,
  showExpiryDate: false,
  showTotalItemsCount: true,
  showTotalUnitsCount: true,

  // Totals & Financials Block
  showSubtotal: true,
  showDiscountTotal: true,
  showNetPayable: true,
  netPayableLabel: 'NET AMOUNT:',
  highlightNetPayable: true,
  netPayableBoxed: false,
  showPaidAmount: true,
  paidLabel: 'PAID:',
  showChangeRefund: true,
  changeRefundLabel: 'CHANGE:',
  showPaymentMethod: true,

  // Footer & Policy Notes
  showFooterGreeting: true,
  footerGreetingText: 'THANK YOU! VISIT AGAIN',
  footerGreetingBold: true,
  showFooterSubGreeting: true,
  footerSubGreetingText: 'Stay Healthy - Stay Safe',
  showReturnPolicy: true,
  returnPolicyTitle: 'NOTICE / RETURN POLICY:',
  returnPolicyText: '1. No return or exchange without original receipt.\n2. Refrigerator medicines & loose tablets are not returnable.\n3. Claim within 3 days of purchase.',
  showBarcode: true,
  showQrCode: true,
  showSoftwareCredit: true,
  softwareCreditText: 'Software by Ali Trader POS • HackTes',
  feedCutLines: 2,
});

export const RECEIPT_PRESETS: { id: string; name: string; description: string; template: (store?: Partial<StoreSettings>) => ReceiptTemplate }[] = [
  {
    id: 'pharmacy_standard',
    name: 'Standard Medical & Pharmacy',
    description: 'Clean medical format with store branding, batch support, return policy notice & barcode.',
    template: (store) => ({
      ...createDefaultReceiptTemplate(store),
      storeNameFontSize: 'large',
      fontFamily: 'monospace',
      dividerStyle: 'dashed',
      showReturnPolicy: true,
      showBarcode: true,
      showQrCode: false,
    }),
  },
  {
    id: 'compact_58mm',
    name: 'Compact 58mm Minimalist (Fast POS)',
    description: 'Narrow 2-inch format with compact line spacing, ideal for mobile bluetooth thermal printers.',
    template: (store) => ({
      ...createDefaultReceiptTemplate(store),
      logoSize: 'small',
      storeNameFontSize: 'normal',
      baseFontSize: 'compact',
      paperPadding: 'compact',
      itemLayout: 'two_line',
      dividerStyle: 'dotted',
      showReturnPolicy: false,
      showQrCode: false,
      showBarcode: true,
      feedCutLines: 1,
    }),
  },
  {
    id: 'supermarket_detailed',
    name: 'Supermarket & Grocery (QR & Barcode)',
    description: 'Comprehensive slip with item discounts, unit breakdown, invoice QR code, and bottom cut lines.',
    template: (store) => ({
      ...createDefaultReceiptTemplate(store),
      fontFamily: 'sans-serif',
      baseFontSize: 'standard',
      dividerStyle: 'solid',
      showItemDiscount: true,
      showTotalItemsCount: true,
      showTotalUnitsCount: true,
      showQrCode: true,
      showBarcode: true,
      netPayableBoxed: true,
      showReturnPolicy: true,
      returnPolicyText: 'Fresh items and frozen foods are non-returnable.\nCustomer Service: 0300-1234567',
    }),
  },
  {
    id: 'modern_bold',
    name: 'Modern Executive / Clean Bold',
    description: 'Prominent bold header and distinct total section with double-line separators.',
    template: (store) => ({
      ...createDefaultReceiptTemplate(store),
      fontFamily: 'courier',
      storeNameFontSize: 'xlarge',
      dividerStyle: 'double',
      highlightNetPayable: true,
      netPayableBoxed: true,
      showReturnPolicy: true,
      showQrCode: true,
      showBarcode: true,
    }),
  },
  {
    id: 'khata_wholesale',
    name: 'Wholesale & Khata Ledger Invoice',
    description: 'Includes customer address, previous credit khata balance, and detailed payment breakdown.',
    template: (store) => ({
      ...createDefaultReceiptTemplate(store),
      fontFamily: 'monospace',
      showCustomerAddress: true,
      showCustomerPhone: true,
      showCustomerPreviousBalance: true,
      showTaxId: true,
      dividerStyle: 'solid',
      netPayableLabel: 'CURRENT BILL TOTAL:',
      showReturnPolicy: true,
      returnPolicyTitle: 'PAYMENT TERMS:',
      returnPolicyText: 'Payment due within 15 days. Please settle outstanding balance.',
    }),
  },
];
